---
- name: Install required packages
  apt:
    name: "{{ web_packages }}"
    state: present
    update_cache: yes

- name: Delete default sites
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx

- name: Replace Nginx
  template:
    src: laravel.nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ site_domain }}.conf"
  notify:
    - reload nginx

- name: Enable Nginx
  file:
    src: "/etc/nginx/sites-available/{{ site_domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ site_domain }}.conf"
    state: link
  notify:
    - reload nginx

- name: Start and enable mysql
  service:
    state: started
    enabled: true
    name: mysql

- name: Start and enable nginx
  service:
    state: started
    enabled: true
    name: nginx
